import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Easy Shop Store",
  description: "Generated by Easy Shop Store",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        <div className="">{children}</div>
        <div className=" ">
          <div className=" bg-gray-400">
            <NavBar />
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
